### ISSUE TITLE
Kwm crashes, sometimes

### ISSUE THREAD

**Issue by koekeishiya** [koekeishiya/kwm#148]
Kwm will sometimes crash, so far no idea what triggers it.
This does not happen frequently for me, and I'm unable to "remember" what sequences of events I went through, during the cases where this happens. This crash happens without the use of external monitors.

**Comment by koekeishiya** [comment]
Note for  future references:
```
(gdb) bt
#0  0x0000000100013c81 in ApplyNodeContainer (Node=0x10000000100714ff, Mode=SpaceModeBSP) at kwm/tree.cpp:500
#1  0x0000000100013cc5 in ApplyNodeContainer (Node=0x10071ab70, Mode=SpaceModeBSP) at kwm/tree.cpp:504
#2  0x0000000100013cc5 in ApplyNodeContainer (Node=0x10071a7a0, Mode=SpaceModeBSP) at kwm/tree.cpp:504
#3  0x0000000100021864 in AddWindowToBSPTree (Screen=0x10060ccc8, WindowID=25725) at kwm/window.cpp:584
#4  0x00000001000204e4 in ShouldBSPTreeUpdate (Screen=0x10060ccc8, Space=0x100213178) at kwm/window.cpp:495
#5  0x000000010001f63c in ShouldWindowNodeTreeUpdate (Screen=0x10060ccc8) at kwm/window.cpp:470
#6  0x000000010001e918 in UpdateWindowTree () at kwm/window.cpp:330
#7  0x0000000100001eee in KwmWindowMonitor () at kwm/kwm.cpp:121
#8  0x00007fff8e945c13 in _pthread_body () from /usr/lib/system/libsystem_pthread.dylib
#9  0x00007fff8e945b90 in _pthread_start () from /usr/lib/system/libsystem_pthread.dylib
#10 0x00007fff8e943375 in thread_start () from /usr/lib/system/libsystem_pthread.dylib
#11 0x0000000000000000 in ?? ()
```
